AFF_ADV_W: 1.0
AFF_DIST: affordance
AFF_LAM0: 1.0
AFF_LAM1: 1.0
AFF_OBS_L: 0
AFF_OBS_R: 39
AFF_TYPE: mul
BC_FINETUNE: true
BC_INIT: true
CHECKPOINT_BASELINE: ''
CHECKPOINT_INVDYN: []
CHECKPOINT_POLICY: ''
CUSTOM_FINGERS: false
CUSTOM_FINGERS_MASK: '11111'
CUSTOM_FRICT: false
CUSTOM_FRICT_MUL: 1.0
CUSTOM_MASS: false
CUSTOM_MASS_MUL: 1.0
CUSTOM_OBJECT: false
CUSTOM_OBJECT_TYPE: box
CUSTOM_OBJ_MASS: false
CUSTOM_OBJ_MASS_MUL: 1.0
CUSTOM_OBJ_SIZE: false
CUSTOM_OBJ_SIZE_MUL: 1.0
DAPG_ADV_W: 0.01
DAPG_BASELINE: false
DAPG_LAM0: 1.0
DAPG_LAM1: 0.95
DEMO_FILE: dapg/dapg/demonstrations/shapenet_pointcloud_mug_traj_0.8_new_select.pkl
DEMO_RATIO: 180
DENSE_REWARD: true
DENSITY: 1000
DENSITY_GEN_MODE: ''
DENSITY_GEN_NUM_TRAJ: 5
DENSITY_GEN_POLICY: ''
DENSITY_LR: 0.001
DENSITY_MB_SIZE: 32
DENSITY_NUM_ITER: 5
DENSITY_OFPG_ADV_W: 1.0
DENSITY_OFPG_LAM0: 1.0
DENSITY_OFPG_LAM1: 1.0
DENSITY_OFPG_MODEL: ''
DENSITY_ONPG_ADV_W: 1.0
DENSITY_ONPG_LAM0: 1.0
DENSITY_ONPG_LAM1: 1.0
DENSITY_ONPG_LR: 0.001
DENSITY_ONPG_MB_SIZE: 32
DENSITY_ONPG_NUM_ITER: 100
DENSITY_ONPG_POS_FRAC: 0.5
DENSITY_ONPG_WS:
- 64
- 64
DENSITY_TRAIN_NEG: ''
DENSITY_TRAIN_POS: ''
DENSITY_TRAIN_POS_FRAC: 0.5
DENSITY_WS:
- 64
- 64
EMB_FILE: null
ENV_NAME: shapenet_pointcloud-mug-0.8
EVAL_RS: 10
FT_BATCHSIZE: 2048
FT_INTERVAL: 20
FT_LR: 0.0003
GAIL:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  WD: 0.0
GAIL_TRPO:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  WD: 0.0
GASIL:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  WD: 0.0
GASIL_OBS_L: 0
GASIL_OBS_R: 39
GASIL_ONPG_ADV_W: 1.0
GASIL_ONPG_LAM0: 1.0
GASIL_ONPG_LAM1: 1.0
GASIL_ONPG_LR: 0.001
GASIL_ONPG_MB_SIZE: 32
GASIL_ONPG_NUM_ITER: 500
GASIL_ONPG_POS_FRAC: 0.5
GASIL_ONPG_WS:
- 64
- 64
GASIL_TYPE: dtw
INVDYN_GEN_MODE: ''
INVDYN_GEN_NUM_TRAJ: 5
INVDYN_GEN_POLICY: ''
INVDYN_LR: 0.001
INVDYN_MB_SIZE: 32
INVDYN_NUM_EP: 5
INVDYN_OFPG_ADV_W: 1.0
INVDYN_OFPG_LAM0: 1.0
INVDYN_OFPG_LAM1: 1.0
INVDYN_OFPG_MODEL: ''
INVDYN_OFPG_NORM: false
INVDYN_OFPG_TEST: false
INVDYN_OFPG_WS:
- 64
- 64
INVDYN_ONPG_ACT_SUBSET: false
INVDYN_ONPG_ADV_W: 1.0
INVDYN_ONPG_AGG: false
INVDYN_ONPG_DEBUG_STATS: false
INVDYN_ONPG_DUMP_INIT: false
INVDYN_ONPG_ENS_N: 1
INVDYN_ONPG_FREEZE: false
INVDYN_ONPG_INC_D: false
INVDYN_ONPG_LAM0: 1.0
INVDYN_ONPG_LAM1: 1.0
INVDYN_ONPG_LONG_N: 0
INVDYN_ONPG_LONG_N_MUL: 5
INVDYN_ONPG_LR: 0.001
INVDYN_ONPG_MB_SIZE: 32
INVDYN_ONPG_MLP_W: 64
INVDYN_ONPG_NORM: false
INVDYN_ONPG_NUM_ITER: 100
INVDYN_ONPG_RBS: 1000000
INVDYN_ONPG_SUBSET: false
INVDYN_ONPG_TEST: false
INVDYN_ONPG_TEST_N: 500
INVDYN_ONPG_TT: false
INVDYN_ONPG_VAL: false
INVDYN_ONPG_VAL_N: 40
INVDYN_ONPG_WD: 0.0
INVDYN_ONPG_WU_ITER: 0
INVDYN_TEST_DATA: ''
INVDYN_TEST_MODEL: ''
INVDYN_TRAIN_DATA: ''
INVDYN_WS:
- 64
- 64
JOB_DIR: ./training_log
JOB_NAME: ilad_ilad_exp
LFA_ADV_W: 0.01
LFA_EVAL_ADV: true
LFA_LAM0: 0.1
LFA_LAM1: 0.99
LFA_LAM2: 0.99
LFA_LAM3: 0.001
LFA_POLICY: false
MATCH_DATA: ''
MATCH_DIST: h_dtw
MATCH_NUM_TRAJ: 5
MATCH_POLICY: ''
NOISE_LEVEL: 0.0
NUM_CPU: 5
NUM_ITER: 1500
NUM_TRAJ: 200
POLICY_INIT_LOG_STD: 0.0
POLICY_LEARN_LOG_STD: true
POLICY_MIN_LOG_STD: -3.0
POLICY_WS:
- 32
- 32
PRIORITY: false
RANDOM_EMBEDDING: false
RNG_SEED: 500
SAMPLER_INIT_STATE: false
SAVE_FREQ: 1
SCRATCH_ADV_W: 1.0
SDAPG_ADV_W: 1.0
SDAPG_DIST: nn
SDAPG_LAM0: 1.0
SDAPG_LAM1: 1.0
SDAPG_OBS_L: 0
SDAPG_OBS_R: 39
SDAPG_TYPE: mul
SL:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  UPDATE_ITV: 5
  WD: 0.0
SOIL:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  WD: 0.0
SPPO:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  WD: 0.0
TRPO:
  ADV_W: 0.1
  CHECKPOINT: ''
  ENABLED: false
  LAM0: 0.1
  LAM1: 0.99
  LR: 0.001
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  UPDATE_ITV: 5
  WD: 0.0
USE_AFF: false
USE_DAPG: false
USE_DENSITY_OFPG: false
USE_DENSITY_ONPG: false
USE_INVDYN_OFPG: false
USE_INVDYN_ONPG: false
USE_LFA: true
USE_SDAPG: false
